language: rust
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev

rust:
  - nightly
  - beta
  - stable
  - 1.0.0
  - 1.1.0
  - 1.2.0

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=nightly
